### ISSUE TITLE
TP1

### ISSUE THREAD

**Issue by fbaglivo** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-lopez_20201c#1]
Hola!

Hago un par de observaciones:

- Diagrama de bloques: no hace falta poner la resistencia y ground.  Solo Fuente, Micro y LED.
- Diagrama circuital: falta el circuito de reset. El micro esta usando el oscilador interno o uno externo?
- Codigo: en ambos casos estas conmutando un solo bit. La idea es que en el caso de puerto entero conmutes el puerto entero.
- Lista de materiales: por favor, agrega los precios estimados de cada componente. Para esto podes entrar en la pagina de algun proveedor y consultar los precios.

**Comment by Santoi** [comment]
Hola Fabricio, gracias por los comentarios.
No había entendido la dinámica del Issue. Ya me suscribí y espero recibir notificaciones a partir de ahora. Pronto envío las correcciones

**Comment by Santoi** [comment]
Fabricio, ya subí las correcciones del tpo1.
Espero tus respuesta.

**Comment by fbaglivo** [comment]
Aprobado con una correccion menor. En el codigo que conmuta un solo led, en la linea 42 reemplaze el 5 por la etiqueta al pin.

**Comment by fbaglivo** [comment]
PD: tenes algun video del sistema funcionando?

**Comment by Santoi** [comment]
Sí. De ambos tps. Ahora chequeo eso que dijiste, se me habrá pasado.

**Comment by Santoi** [comment]
Ya subidos al directorio ./doc/otros/
